/*
    BLOGS 
*/

//REDUCER
export const FETCH_BLOGS_REDUCER = "FETCH_BLOGS_REDUCER"
export const RECEIVE_BLOGS_REDUCER = "RECEIVE_BLOGS_REDUCER"

export const RECEIVE_COMMENTS_FOR_BLOGS_REDUCER = "RECEIVE_COMMENTS_FOR_BLOGS_REDUCER"
export const DELETE_BLOG_REDUCER = "DELETE_BLOG_REDUCER"
export const ADD_BLOGPOST_REDUCER = "ADD_BLOGPOST_REDUCER"

//TYPES
export const FETCH_BLOGS_TYPE = "FETCH_BLOGS_TYPE"
export const RECEIVE_BLOGS_TYPE = "RECEIVE_BLOGS_TYPE"
export const FETCH_COMMENTS_FOR_BLOGS_TYPE = "FETCH_COMMENTS_FOR_BLOGS_TYPE"
export const DELETE_BLOG_TYPE = "DELETE_BLOG_TYPE"
export const ADD_BLOGPOST_TYPE = "ADD_BLOGPOST_TYPE"
/*
    COMMENTS 
*/

//REDUCER
export const FETCH_COMMENTS_REDUCER = "FETCH_COMMENTS_REDUCER"

//TYPES
export const FETCH_COMMENTS_TYPE= "FETCH_COMMENTS_TYPE"
